name: WebSql
version: 1.3.0
summary: Azure Web App and SQL Database Environment
description: Deploys a web app, sql db, application insights
runner: ARM
templatePath: main.json
parameters:
- id: "prefix"
  name: "prefix"
  description: "prefix name for unique id"
  default: ""
  type: "string"
  required: true
- id: "region"
  name: "region"
  description: "Azure region for deployed resources"
  default: ""
  type: "string"
  required: true