name: WebSql
version: 1.4.1
summary: Azure Web App and SQL Database Environment
description: Deploys a web app, sql db, application insights
runner: ARM
templatePath: main.bicep
parameters:
- id: "region"
  name: "region"
  description: "Azure region for deployed resources"
  type: "string"
  required: false
  allowed:
    - 'swedencentral'
    - 'eastus2'
    - 'southeastasia'
  default: "swedencentral"
  