name: WebSql
version: 1.3.3
summary: Azure Web App and SQL Database Environment
description: Deploys a web app, sql db, application insights
runner: ARM
templatePath: main.bicep
parameters:
- id: "region"
  name: "region"
  description: "Azure region for deployed resources"
  default: ""
  type: "string"
  required: true