name: APIM-AOAI-LoadBalance
version: 1.0.5
summary: Deploy API management and Azure OpenAI Service as Backend pool
description: Deploy API management and Azure OpenAI Service as Backend pool
runner: ARM
templatePath: main.bicep
parameters:
- id: "apimRegion"
  name: "apimRegion"
  description: "region for main resources"
  type: "string"
  required: true

- id: "aoaiRegion1"
  name: "aoaiRegion1"
  description: "apim backend openai region"
  type: "string"
  required: false

- id: "aoaiRegion2"
  name: "aoaiRegion2"
  description: "apim backend openai region"
  type: "string"
  required: true

- id: "modelSku"
  name: "modelSku"
  description: "openai deployment model"
  type: "string"
  required: true
  allowed:
    - "Standard"

- id: "modelName"
  name: "modelName"
  description: "openai deployment model"
  type: "string"
  required: true
  allowed:
    - "gpt-4o"

- id: "modelVersion"
  name: "modelVersion"
  description: "openai deployment model"
  type: "string"
  required: true
  allowed:
    - "2024-05-13"

- id: "modelCapacity"
  name: "modelCapacity"
  description: "openai deployment model"
  type: "integer"
  required: true

