name: Functions-dotnet
version: 1.2.0
summary: Azure Functions with Storage account with Queue and Blob
description: Deploys functions, storage, application insights
runner: ARM
templatePath: main.bicep
parameters:
- id: "region"
  name: "region"
  description: "Azure region for deployed resources"
  default: ""
  type: "string"
  required: true